### ISSUE TITLE
question about model

### ISSUE THREAD

**Issue by zzwu29** [konan6915/SuperPointCPP#2]
Great work!
I have a question whether all the files (**.pt or .pth**) in **./model/** directory are valid for this source code. I found that both superpoint_v2.pt and superpoint_v3_t.pt work well, but the other two files could not work.
Or, could you please tell me the differences between them?

Thank you!

**Comment by konan6915** [comment]
Pytorch的模型文件保存为.pth文件，C++接口一般读取的是.pt文件，C++在调用Pytorch训练好的模型文件的时候就需要进行一个转换，转换为.pt文件，才能够读取。至于./model/文件夹下的文件，.pth文件是原来未转换的，v2和v3是转换后的，具体的差别忘了，v3是最终的版本。

**Comment by zzwu29** [comment]
> Pytorch的模型文件保存为.pth文件，C++接口一般读取的是.pt文件，C++在调用Pytorch训练好的模型文件的时候就需要进行一个转换，转换为.pt文件，才能够读取。至于./model/文件夹下的文件，.pth文件是原来未转换的，v2和v3是转换后的，具体的差别忘了，v3是最终的版本。

请问如何实现这个转换呢？

**Comment by konan6915** [comment]
https://blog.csdn.net/weixin_42329982/article/details/107840908，你可以自己试一试，我的测试代码忘了放哪了。。。

**Comment by konan6915** [comment]
[转换代码例子](https://blog.csdn.net/weixin_42329982/article/details/107840908)，你可以自己试一试，我的测试代码忘了放哪了。。。

**Comment by zzwu29** [comment]
谢谢~
